---

- name: Create {{ item.path }}, if needed.
  block:
    - name: Check if {{ item.path }} already exists to prevent permission changes.
      ansible.builtin.stat:
        path: "{{ item.path }}"
      register: directory

    - name: Create {{ item.path }} directory.
      ansible.builtin.file:
        dest: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      when: not directory.stat.exists
  tags:
    - compose-directories
