---

- name: Place compose apps configuration files at {{ item.path }}.
  block:
    - name: Ensure {{ item.path }} directory exists.
      include_tasks: compose-directories.yml
      loop: "{{ lookup('list', item, wantlist=True) }}"
      loop_control:
        loop_var: i

    - name: Copy {{ item.file }} to {{ item.path }}.
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.path }}/{{ item.file }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        force: "{{ item.force }}"
      when: item.template is false

    - name: Set template {{ item.file }} to {{ item.path }}.
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.path }}/{{ item.file }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        force: "{{ item.force }}"
      when: item.template is true

  tags:
    - compose-configuration-files

